<?xml version="1.0" ?>
<testsuite name="WebTests-20210218191626" tests="3" time="1.310" failures="0" errors="2">
	<testcase classname="WebTests" name="test_3_combine_the_results" time="0.000"/>
	<testcase classname="WebTests" name="test_1_open_amazon_and_fetch_results" time="0.970">
		<error type="WebDriverException" message="Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=88.0.4324.182)
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Depinder Bharti\PycharmProjects\pythonProject\main2.py", line 29, in test_1_open_amazon_and_fetch_results
    self.driver.get("http://amazon.com")
  File "C:\Users\Depinder Bharti\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Depinder Bharti\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Depinder Bharti\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=88.0.4324.182)

]]></error>
	</testcase>
	<testcase classname="WebTests" name="test_2_open_ebay_and_fetch_results" time="0.340">
		<error type="WebDriverException" message="Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=88.0.4324.182)
"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Depinder Bharti\PycharmProjects\pythonProject\main2.py", line 43, in test_2_open_ebay_and_fetch_results
    self.driver.get("http://amazon.com")
  File "C:\Users\Depinder Bharti\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Depinder Bharti\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Depinder Bharti\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=88.0.4324.182)

]]></error>
	</testcase>
	<system-out><![CDATA[Init - Setting up web browser
TestCase: 1 - Open Amazon and fetch results for Iphone 11
TestCase: 2 - Open Ebay and fetch results for Iphone 11
TestCase: 3 - Fetch values from Global and handle data
TearDown - End of Test Scenario
]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
